#!/bin/sh
 
case "$*" in
    \**) /usr/bin/firefox http://m.juick.com/tag?tag=$(echo "$*" | sed 's/*//') ;;
    \#[0-9][0-9][0-9][0-9][0-9]*) /usr/bin/firefox http://m.juick.com/$(echo "$*" | sed 's/#//' | sed 's/\//#/') ;;
    \#[a-z]*) /usr/bin/firefox http://m.psto.net/$(echo "$*" | sed 's/#//' | sed 's/\//#/') ;;
    \#[A-Z0-9]*) /usr/bin/firefox http://bnw.im/p/$(echo "$*" | sed 's/#//' | sed 's/\//#/') ;;
    \@*) /usr/bin/firefox http://m.juick.com/$(echo "$*" | sed 's/@//') ;;
esac
 
